name: 修正工作区路径的部署脚本

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 显示工作区路径（调试用）
        run: |
          echo "当前工作区路径: ${{ github.workspace }}"
          # 输出路径结构，确认文件存放位置
          ls -la

      - name: 设置Go环境
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false

      - name: 编译程序
        run: |
          GOOS=linux GOARCH=amd64 go build -o myapp main.go
          chmod +x myapp
          # 确认编译文件在工作区内
          echo "编译文件位置: $(pwd)/myapp"
          ls -l myapp

      - name: 部署到服务器
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.TEST_SERVER_HOST }}
          username: ${{ secrets.TEST_SERVER_USER }}
          key: ${{ secrets.TEST_SERVER_SSH_KEY }}
          port: ${{ secrets.TEST_SERVER_PORT || 22 }}
          script: |
            TARGET_DIR="/home/testapp"
            mkdir -p $TARGET_DIR
            
            pkill -f "$TARGET_DIR/myapp" || true
            sleep 1
            
            # 准备私钥
            echo "${{ secrets.TEST_SERVER_SSH_KEY }}" > /tmp/deploy_key
            chmod 600 /tmp/deploy_key
            
            # 使用正确的工作区路径（通过${{ github.workspace }}变量自动获取）
            scp -o StrictHostKeyChecking=no -i /tmp/deploy_key -P ${{ secrets.TEST_SERVER_PORT || 22 }} \
              ${{ github.workspace }}/myapp \
              ${{ secrets.TEST_SERVER_USER }}@${{ secrets.TEST_SERVER_HOST }}:$TARGET_DIR/myapp
            
            rm -f /tmp/deploy_key
            
            # 验证文件传输
            if [ ! -f "$TARGET_DIR/myapp" ]; then
              echo "错误：文件未传输到服务器"
              exit 1
            fi
            
            chmod +x $TARGET_DIR/myapp
            nohup $TARGET_DIR/myapp > $TARGET_DIR/app.log 2>&1 &
            
            sleep 2
            if pgrep -f "$TARGET_DIR/myapp"; then
              echo "部署成功"
            else
              echo "启动失败，日志："
              cat $TARGET_DIR/app.log
              exit 1
            fi
