name: 编译并部署到测试服务器

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 设置Go环境
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: 编译程序
        run: |
          GOOS=linux GOARCH=amd64 go build -o myapp main.go
          ls -l myapp  # 确认编译成功

      - name: 部署到测试服务器
        uses: appleboy/ssh-action@v1.0.3  # 使用固定版本，避免兼容性问题
        with:
          host: ${{ secrets.TEST_SERVER_HOST || 101.200.230.240 }}
          username: ${{ secrets.TEST_SERVER_USER || "root"}}
          key: ${{ secrets.TEST_SERVER_SSH_KEY || ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDI+7hNTNn5xAb31N0edrqI10J219Wk7PMkq5rUhE2oHxhoiN5cDOQyMTRTMCqOIl+nBVqOtLuDMP/lU5ZRK7vRdzr1UsWdtYMRf7CDC7KHdABNn+BYN9LqIsGeHwxAjr7XCgh871YbEa/efcB5S36cl517Lz8yxcqMba/AhGKIZWFPSTEAN1kfcTSKRs+sZR98flVz6+FwhENlW7BO8qIYEaIv4q2GIUAmJxen8Zgd5WSmMQgqpuvztvukxrjWougAHU0oPzLhc7c6q0caiM0eqO+3/qsqmH7f7oR0OjrEoOqSqut0GFTj5tiLVU1+8BU61v+/APbwlmveYlTySq1p root@iZ2ze1zykik3obzetjrye4Z }}
          port: ${{ secrets.TEST_SERVER_PORT || 22 }}
          # 使用scp命令传输文件（替代原来的source/target）
          script: |
            # 确保服务器目标目录存在
            mkdir -p /home/testapp
            
            # 停止当前运行的程序
            pkill myapp || true
            
            # 备份旧版本
            mv /home/testapp/myapp /home/testapp/myapp_old || true
            
            # 从工作流环境复制文件到服务器（使用here-document语法）
            cat > /home/testapp/myapp << 'EOF'
            ${{ github.workspace }}/myapp
            EOF
            
            # 赋予执行权限
            chmod +x /home/testapp/myapp
            
            # 启动程序（根据需要添加）
            nohup /home/testapp/myapp &
