name: 全链路追踪myapp文件状态

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 检查源代码
        run: |
          echo "=== 源代码检查 ==="
          ls -l main.go || echo "main.go不存在"

      - name: 编译并记录文件状态
        run: |
          echo "=== 编译前状态 ==="
          ls -l myapp || echo "myapp初始不存在"
          
          # 编译
          GOOS=linux GOARCH=amd64 go build -o myapp main.go
          
          echo "=== 编译后状态 ==="
          # 检查存在性
          if [ ! -f "myapp" ]; then
            echo "编译失败：myapp未生成"
            exit 1
          fi
          # 检查权限
          ls -l myapp  # 应显示-rwxr-xr-x
          # 检查文件类型
          file myapp    # 应显示ELF可执行文件
          # 记录绝对路径
          echo "myapp绝对路径: $(readlink -f myapp)"
          # 计算文件哈希（用于验证完整性）
          sha256sum myapp > myapp.sha256
          cat myapp.sha256

      - name: 传输前再次确认
        run: |
          echo "=== 传输前检查 ==="
          # 再次验证文件存在
          if [ ! -f "myapp" ]; then
            echo "错误：传输前myapp消失"
            exit 1
          fi
          # 验证哈希（确保文件未被篡改）
          sha256sum -c myapp.sha256 || echo "文件已被修改"
          # 输出工作区绝对路径
          echo "工作区绝对路径: $(readlink -f ${{ github.workspace }})"
          # 确认工作区中存在文件
          ls -l ${{ github.workspace }}/myapp

      - name: 部署到服务器
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.TEST_SERVER_HOST }}
          username: ${{ secrets.TEST_SERVER_USER }}
          key: ${{ secrets.TEST_SERVER_SSH_KEY }}
          port: ${{ secrets.TEST_SERVER_PORT || 22 }}
          script: |
            TARGET_DIR="/home/testapp"
            mkdir -p $TARGET_DIR
            
            # 传输文件
            echo "${{ secrets.TEST_SERVER_SSH_KEY }}" > /tmp/deploy_key
            chmod 600 /tmp/deploy_key
            
            echo "=== 开始传输 ==="
            # 传输时显示详细日志

            scp -o StrictHostKeyChecking=no -i /tmp/deploy_key -P ${{ secrets.TEST_SERVER_PORT || 22 }} \
              ${{ github.workspace }}/main.go \
              ${{ secrets.TEST_SERVER_USER }}@${{ secrets.TEST_SERVER_HOST }}:$TARGET_DIR
            
            
            # 传输后验证
            echo "=== 服务器端验证 ==="
            if [ ! -f "$TARGET_DIR/myapp" ]; then
              echo "错误：服务器上myapp不存在"
              exit 1
            fi
            # 检查文件类型和权限
            ls -l $TARGET_DIR/myapp
            file $TARGET_DIR/myapp
            # 尝试执行（直接显示错误）
            $TARGET_DIR/myapp || echo "执行失败，继续排查"
