name: 编译并部署到测试服务器

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 设置Go环境
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: 编译程序
        run: |
          GOOS=linux GOARCH=amd64 go build -o myapp main.go
          ls -l myapp  # 确认编译成功

      - name: 打印调试信息
        run: |
          echo "===== 调试信息 ====="
          echo "TEST_SERVER_HOST: ${{ secrets.TEST_SERVER_HOST || '未设置' }}"
          echo "TEST_SERVER_USER: ${{ secrets.TEST_SERVER_USER || '未设置' }}"
          echo "TEST_SERVER_PORT: ${{ secrets.TEST_SERVER_PORT || '未设置（使用默认22）' }}"
          # 注意：不要打印TEST_SERVER_SSH_KEY的完整值，这里只检查是否存在
          if [ -n "${{ secrets.TEST_SERVER_SSH_KEY }}" ]; then
            echo "TEST_SERVER_SSH_KEY: 已设置（长度：${{ length(secrets.TEST_SERVER_SSH_KEY) }}）"
          else
            echo "TEST_SERVER_SSH_KEY: 未设置"
          fi
          echo "===================="
          
      - name: 部署到测试服务器
        uses: appleboy/ssh-action@v1.0.3  # 使用固定版本，避免兼容性问题
        with:
          host: ${{ secrets.TEST_SERVER_HOST }}
          username: ${{ secrets.TEST_SERVER_USER }}
          key: ${{ secrets.TEST_SERVER_SSH_KEY }}
          port: ${{ secrets.TEST_SERVER_PORT || 22 }}
          # 使用scp命令传输文件（替代原来的source/target）
          script: |
            # 确保服务器目标目录存在
            mkdir -p /home/testapp
            
            # 停止当前运行的程序
            pkill myapp || true
            
            # 备份旧版本
            mv /home/testapp/myapp /home/testapp/myapp_old || true
            
            # 从工作流环境复制文件到服务器（使用here-document语法）
            cat > /home/testapp/myapp << 'EOF'
            ${{ github.workspace }}/myapp
            EOF
            
            # 赋予执行权限
            chmod +x /home/testapp/myapp
            
            # 启动程序（根据需要添加）
            nohup /home/testapp/myapp &
